# Generated by Django 4.1.2 on 2022-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Siniflar",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("numbers", models.IntegerField()),
                ("female", models.IntegerField()),
                ("male", models.IntegerField()),
                ("department", models.CharField(max_length=200)),
            ],
        ),
    ]
