# Generated by Django 4.1.2 on 2022-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sinif", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siniflar",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
