# Generated by Django 4.1.2 on 2022-10-29 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("sinif", "0002_siniflar_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siniflar",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
