# Generated by Django 4.1.2 on 2022-10-29 10:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sinif", "0003_alter_siniflar_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ogrenciler",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gano", models.FloatField()),
                ("gender", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "sinif",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sinif.siniflar",
                    ),
                ),
            ],
        ),
    ]
